### ISSUE TITLE
DLC & Workshop UI overlap

### ISSUE THREAD

**Issue by cmkohnen** [tkashkin/Adwaita-for-Steam#101]
Both DLC and Workshop item list in game properties overlap with their respective header

![grafik](https://user-images.githubusercontent.com/59118042/215262345-51f3eb82-dbbc-4bb6-913a-c39cd4eb2806.png)
![grafik](https://user-images.githubusercontent.com/59118042/215262356-df1c61dd-478a-4960-8fc0-633dc0b762e5.png)

**Comment by tkashkin** [comment]
Should be fixed by #102.

**Comment by tkashkin** [comment]
@Foldex A couple of small related issues:

1. These checkboxes should be styled as regular checkboxes and not as switches if it's possible.
If not, maybe there's a way to at least move them to the right side where switches are usually placed.
2. There should be no horizontal scroll here.
3. Buttons and search bars look weird, something more similar to [GNOME search bars](https://developer.gnome.org/hig/patterns/nav/search.html) would be ideal.
Not sure what to do with the buttons, maybe it's possible to move them to the headerbar or somewhere below the list.

**Comment by Foldex** [comment]
@tkashkin 

1: Should be done as part of #109
3: Putting the issue of where to shove the other button aside, search is a bit iffy.
![image](https://user-images.githubusercontent.com/47908676/217696359-0a0ddcff-64db-43e0-b79a-bfe7f684a586.png)

Typically adwaita search is hidden and slides in as a result of type to search or ctrl-f, neither of which will obviously work here. Having it always visible center screen feels off, since it's supposed to be out of the way when not in use. Maybe it's still preferable to steam's layout, but eh. Dunno if you have any ideas here.
