### ISSUE TITLE
Download Progress Bar in Library

### ISSUE THREAD

**Issue by WMan22** [tkashkin/Adwaita-for-Steam#11]
This steam theme provides good consistency across Adwaita apps, but what it doesn't have is the download progress bar on the bottom of the steam window that is there in the original theme, it would be nice to have that somewhere visible, even if it's miniaturized and put to the right of "Community" or to the left of your profile image as to not waste the screen space that has been freed up by using this theme. 

It means that I don't have to click "Downloads" under the library tab to see download progress just like on vanilla steam.

**Comment by tkashkin** [comment]
The downloads button is currently hidden because there are just too many buttons in the headerbar and I'm not sure where to place it.

You can show it by editing `Adwaita/resource/layout/steamrootdialog.layout`, move `UIStatusPanel` from line 17 to line 10, for example:

```
place { control="InboxButton,SupportAlert,ParentalLockButton,UIStatusPanel,MenuBar" width=34 height=34 y=7 margin-right=12 spacing=6 align=right end-right="frame_minimize" }
```

Maybe just an OSD progress bar when downloads are in progress would be enough? It is [a pattern in GNOME HIG](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/style-classes.html#progress-bars), except it's usually not clickable:
![image](https://user-images.githubusercontent.com/2003017/185766882-efaafeba-2ee3-408d-bccc-760e16476eb4.png)

**Comment by tkashkin** [comment]
I guess that works. Looks a bit weird with the URL bar visible but it's not that bad.

![image](https://user-images.githubusercontent.com/2003017/185767379-6a8aae3b-65e3-4ff8-bfe4-6785afd8b2fb.png)
![image](https://user-images.githubusercontent.com/2003017/185767468-3d1867f2-dbd5-481b-95c0-943e5aa1623d.png)

**Comment by WMan22** [comment]
Would have been nice to have the "1 of 3 downloads" or something somewhere but having any bar indicating download progress at all is good enough for me personally, thank you. I especially appreciate how thin you made it, takes up basically a pixel or two's worth of vertical screen real estate. I would have the number of downloads display something like this if at all possible.
![Screenshot from 2022-08-20 16-44-10](https://user-images.githubusercontent.com/48204719/185769612-a3057abd-c23d-4f60-9654-b56854dfc4ef.png)

[](url)
