### ISSUE TITLE
Patch executable not found in $PATH. Make sure you have GNU Patch installed

### ISSUE THREAD

**Issue by Nextovoy** [tkashkin/Adwaita-for-Steam#147]
Hi. Please tell me what this error means and how it can be fixed?

![image](https://user-images.githubusercontent.com/6684427/235445083-c0da6286-477b-4576-b1ad-7a8cd4b65fc6.png)

**Comment by Foldex** [comment]
You do not have `patch` installed, or it is installed somewhere that is not included in the `$PATH` environment variable and therefore cannot be found:
Since [patch](https://software.manjaro.org/package/patch) is part of the manjaro `core` repo, it should have come with your install, unless you removed it somehow.
