### ISSUE TITLE
Space for Name is too short, no minimize and no button for friendlist intended?

### ISSUE THREAD

**Issue by kskruffnekk** [tkashkin/Adwaita-for-Steam#16]
Hello there,

see attached. My profile name seems to be too long, so it gets cut. Is there a solution?

Futhermore, there doesn't seem to be a mini- or maximize button, is that intended? On top, there is no button for the friendlist, I have to use rightclick - friendlist from my steam-taskbar-button.

I am using Fedora 36, Steam package is from rpmfusion.

![steam](https://user-images.githubusercontent.com/108282882/188260522-3b96df11-8326-429e-95ec-dc76ab73e1da.png)

**Comment by tkashkin** [comment]
> My profile name seems to be too long, so it gets cut. Is there a solution?

Not really:
* All buttons are 120px wide like in GNOME [ViewSwitcher](https://developer.gnome.org/hig/patterns/nav/view-switchers.html).
* You'd probably have the same issue if a native libadwaita app did the same thing and tried to display a long string as a `ViewSwitcher` tab.
* You can increse width of the buttons [here](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/resource/layout/uinavigatorpanel.layout#L11), then you will need to [adjust the positions of icons](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/adw/rootdialog.styles#L358-L380).
* You can completely remove `width=120` from `uinavigatorpanel.layout` to let the buttons wrap their text, but then the icons won't line up and it won't look like `Adw.ViewSwitcher`.

> there doesn't seem to be a mini- or maximize button, is that intended?

Yes, because that's how GNOME looks by default. There is an installer script that has a few window controls presets, see the [Installation](https://github.com/tkashkin/Adwaita-for-Steam#installation) section of the readme or #13.

> On top, there is no button for the friendlist

It was removed because there were too many buttons there for smaller window sizes.

You can add it back by editing [`steamrootdialog.layout`](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/resource/layout/steamrootdialog.layout). Move `view_friends` control from [line 18](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/resource/layout/steamrootdialog.layout#L18) to [line 11](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/resource/layout/steamrootdialog.layout#L11), for example
```
place { control="InboxButton,SupportAlert,ParentalLockButton,view_friends,MenuBar"
```
