### ISSUE TITLE
Make color themes plain CSS

### ISSUE THREAD

**Issue by tkashkin** [tkashkin/Adwaita-for-Steam#178]
There's no need to replace VGUI colors anymore, so there's no need for custom `.theme` format.
Plain CSS will be easier to work with and more flexible if themes need to change more than colors.

**Comment by Foldex** [comment]
I'll chime in and say obviously it made more sense when we needed to patch two different file formats, which is no longer the case. Pure CSS would be cleaner as far as this project is concerned.

That said, AdwSteamGtk does currently parse `.theme` files in order to preview theme colors. Probably can be worked around, but it's worth noting.

**Comment by tkashkin** [comment]
@Foldex I forgot about the color preview.

Unfortunately custom color format in GTK CSS is different and it won't be possible to just load the CSS directly.

It shouldn't be too hard to read the CSS file, find all lines like `--$colorname: $color;`, and generate GTK CSS like it does currently, but yes, that's still a bit harder than just reading the colors with `configparser`.
