### ISSUE TITLE
Library hover options impossible to click

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [tkashkin/Adwaita-for-Steam#196]
![Kooha-2023-08-01-12-30-51](https://github.com/tkashkin/Adwaita-for-Steam/assets/13170204/5f2122b1-de8c-4ab7-b3eb-25c6e564a141)
Make adding a non-steam shortcut, impossible, especially with no-way to revert back to the old titlebar.

**Comment by tkashkin** [comment]
These menus and other similar popups are still a bit buggy and sometimes they break even without any modifications to the Steam client. Try restarting Steam and see if the menu is working.

And yes, the menu buttons appearing on hover are not great, but there's nowhere else to put that menu otherwise.
Maybe we can merge all menus into one and remove some of the less useful items.
This can't be done in CSS only and would require JS patching. (#179, https://github.com/tkashkin/Adwaita-for-Steam/discussions/181#discussioncomment-6455199)

**Comment by PoorPocketsMcNewHold** [comment]
I now, can easily use the Library hover buttons. Did anything like https://github.com/tkashkin/Adwaita-for-Steam/pull/199 happened, or is it just unreliable? (Mainly asking if this should be closed or not, as for me, it does work now.)

**Comment by tkashkin** [comment]
Nothing was fixed in the skin. Popups seem to break randomly, especially when the client was running for some time. Restarting Steam usually helps.

Not much we can do anyway without JS patches or just hiding the menu, so I guess you can close this.
