### ISSUE TITLE
Support for colors?

### ISSUE THREAD

**Issue by Doomsdayrs** [tkashkin/Adwaita-for-Steam#22]
There are applications that can change the color scheme like [Gradience](https://github.com/GradienceTeam/Gradience), Possible support for that?

**Comment by tkashkin** [comment]
Color theme support was implemented in #106 and is available in the [latest release](https://github.com/tkashkin/Adwaita-for-Steam/releases/tag/v0.30).

There are a few presets and you can [make your own themes](https://github.com/tkashkin/Adwaita-for-Steam/blob/master/extras/colorthemes/README.md).

This should also make creating things like a Gradience plugin much easier because now it only needs to generate a color scheme and run a script to recolor graphics assets.
