### ISSUE TITLE
Graphical glitches when moving mouse cursor to hamburger icon in headerbar

### ISSUE THREAD

**Issue by heldderarbeit** [tkashkin/Adwaita-for-Steam#263]
I'm on Arch, Gnome Wayland and installed AdwSteamGtk from Flathub (v. 0.6.11). When I move the mouse cursor to the hamburger icon in the headerbar, the profile icon rapidly changes back and forth to an "information" symbol (and the 3 icons right of it also glitch around).
This is all happening just by leaving the mouse cursor on the hamburger icon, I don't have to manually move it to trigger this behaviour.

[Screencast from 2024-08-14 08-59-36.webm](https://github.com/user-attachments/assets/14f4606d-204d-4512-8064-755134b5994c)

**Comment by ExposedCat** [comment]
Same issue, but shows avatar when not hovered and generic icons when hovered (no intermediate flickering)

**Comment by tkashkin** [comment]
Changing icons is not a bug. The icons appearing on hover are Steam's default menu items (Steam, View, Games, Friends, Help).

You can access all of them by clicking on the menu button and hovering while the menu is open.

It's done like this because there is no way to modify the menus without patching JavaScript (this skin is still CSS-only), and because there's nowhere else to put 4 other less frequently used icons.

This way it still looks like a regular GNOME app, but the entire main menu remains accessible if needed.

**Comment by tkashkin** [comment]
@heldderarbeit Can't reproduce the flickering now.
Feel free to reopen if it still happens, but I don't know if it can be fixed.

**Comment by ExposedCat** [comment]
@tkashkin thanks for explanation, it makes sense
