### ISSUE TITLE
Utilize the system font by default.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [tkashkin/Adwaita-for-Steam#272]
I use this theme to make Steam more consistent with the rest of my DE, since [it supports Breeze](https://github.com/tkashkin/Adwaita-for-Steam/discussions/264#discussion-7051994) ([at least, the Dark theme](https://github.com/tkashkin/Adwaita-for-Steam/discussions/270#discussion-7178371)). However, it sets a font that I don't find particularly readable. This is unexpected, because no other software I utilize (bar those written in Electron) do so.

I believe that this behaviour is incorrect, because it's a significant accessibility disadvantage. Consider someone with dyslexia - why should [they need to learn CSS](https://github.com/tkashkin/Adwaita-for-Steam/pull/173/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R135-R151) merely so that they can read what's on the display?

If this would be better posted at https://github.com/Foldex/AdwSteamGtk/issues/new?assignees=&labels=enhancement&projects=&template=feature-request.md&title=Feature+Request%3A+, I'll acquiesce.

**Comment by tkashkin** [comment]
> This is unexpected, because no other software I utilize (bar those written in Electron) do so.

Steam is basically this - a cross-platform web app that doesn't look native anywhere. It uses CEF and not Electron - same thing mostly.

No way to use system fonts from CSS directly. Maybe we can read system settings from somewhere in installer script.

* But what even is "the system font"?
* Which one to use for what if there are multiple?
* Where are they stored on each platform and DE?
* How to get them?
* Does Steam web view have access to them?
* Will they need size and weight changes from what's used now with Cantarell to look good everywhere?
* Will they break layout somewhere if they have very different metrics?

That's too many questions and it's not something I want to support.

At most I could add an option to set the font name, but just the font name might not always be enough.
You can already change fonts with a few lines of CSS, and more importantly you can tweak anything in the same CSS if needed.

**Comment by beedell-roke** [comment]
<blockquote>

No way to use system fonts from CSS directly. Maybe we can read system settings from somewhere in installer script.

* But what even is "the system font"?

</blockquote>

@tkashkin, CEF utilises the Chromium engine, which implements support for `system-ui`.

> * Which one to use for what if there are multiple?

`system-ui` provides an ordered list. The first is the preferred option.

> * Where are they stored on each platform and DE?

KDE Plasma stores them in `grep -i "font" ~/.config/kdeglobals`. However, this doesn't matter, because `system-ui` obfuscates this. Though, even if it didn't:

> * How to get them?

DE | Method
-|-
KDE Plasma | `kreadconfig6 --file kdeglobals --group General --key font`
GNOME | `gsettings get org.gnome.desktop.interface document-font-name`

> * Does Steam web view have access to them?

Yes. Even in Flatpak, a default shall be provided, which can be overridden to acquire the real default. That has been solved in most DEs.

> * Will they need size and weight changes from what's used now with Cantarell to look good everywhere?

Inherently, the user's font can cause problems. However, the DE defaults equivalate Steam's (and vice versa), and no DE offers support for larger font sizes. That's what display scales are for.

> * Will they break layout somewhere if they have very different metrics?

Likely, but that is as the aforementioned describes. That's user error, that can solely occur if the user deliberately sets absurd preferences, and it would break all other applications, too.

> You can already change fonts with a few lines of CSS, and more importantly you can tweak anything in the same CSS if needed.

Considering that even `* { font-family: system-ui }` would be an accessibility and aesthetic improvement, per the work done at [`issues/336#issuecomment-4533012782`](https://github.com/tkashkin/Adwaita-for-Steam/issues/336#issuecomment-4533012782) for similar system adherence, I'm surprised that this is undesirable.

</blockquote>

**Comment by tkashkin** [comment]
bed4fe3 adds `--font system` option. I was sure it didn't work the last time I looked into it, but now it does work.

Font sizes will still need custom CSS if users want to change them, that's not something I want to support as a builtin option.
