### ISSUE TITLE
No scrollbars

### ISSUE THREAD

**Issue by Vovkiv** [tkashkin/Adwaita-for-Steam#275]
![зображення](https://github.com/user-attachments/assets/6893db10-6e74-48b9-a28b-7f14512591cc)

![зображення](https://github.com/user-attachments/assets/31af8300-b2a6-484a-a5af-153e879d59e4)

After switching to beta branch and latest adwaita theme, seems that all scrollbars disappeared?
In settings window, in library, in chat window.

**Comment by tkashkin** [comment]
That's a known issue.

New CEF dropped support of `overflow: overlay` property that was used to make scrollbars overlay the content instead of taking additional space.

Scrollbars are temporarily hidden in the current theme version while I try to figure out how to make them less ugly without overlay support.
