### ISSUE TITLE
Release it as a flapak extension 

### ISSUE THREAD

**Issue by marc0x1** [tkashkin/Adwaita-for-Steam#34]
I don't know if is technically possible, but if this theme is release as a flatpak extension or a COPR repo on fedora, users could enjoy autoupdate. 
Steam on flatpak has extension that the user can install directly like Proton-GE

**Comment by Foldex** [comment]
The flatpak steam maintainers probably know more on the subject of how feasible this would be, but:
As I understand it, flatpak extensions conform to adding their data under `/app` within the sandbox. However that wouldn't fall under the locations that steam checks for a skin.

The reason custom compatibility tools like Proton-GE are able to be sourced by flatpak is due to Valve implementing the [STEAM_EXTRA_COMPAT_TOOLS_PATHS](https://github.com/ValveSoftware/steam-for-linux/issues/6310) environment variable. You can see it set in steam's flatpak manifest [here](https://github.com/flathub/com.valvesoftware.Steam/blob/8311ec12289021267ddd7a5ba1152678d31bd0c0/com.valvesoftware.Steam.yml#L68).
But to my knowledge there's no similar implemented option to allow steam to source skins from a custom directory, though maybe Valve could be convinced to provide one.
I guess using flatpak steam's [wrapper](https://github.com/flathub/com.valvesoftware.Steam/blob/beta/steam_wrapper/steam_wrapper.py) you might be able to copy (steam doesnt like symlinks for skins)  directories under something like  `/app/share/steam/skins.d` to the usual `~/.var/app/com.valvesoftware.Steam/data/Steam/skins` before steam loads, but this sounds somewhat hacky.

The other issue is that parts of the theme are customizable and the flatpak filesystem is read only. Unlike a ready to go proton binary we cant simply point to it. I guess one could provide pregenerated variants under `/app` so long as there aren't too many, but it would still depend on the above functionality.

**Comment by marc0x1** [comment]
Oh sorry, i didn't know that. Thanks for the amazing job you are doing!
