### ISSUE TITLE
Why are top bar items aligned to left?

### ISSUE THREAD

**Issue by muznyo** [tkashkin/Adwaita-for-Steam#37]
![image](https://user-images.githubusercontent.com/24987471/194723721-6f49541d-b0cf-43be-aa11-7a1d4668a3e2.png)
I don't know if that's intentional, but it looks weird.

**Comment by meisme-dev** [comment]
Yeah it looks really strange, I think it should be centered

**Comment by tkashkin** [comment]
VGUI styles are limited. It's not possible to change the label's alignment.
Even if it was possible, the icons are not actually part of the buttons and it would be impossible to center them with the text if each label has different width.

So no, it's not really intentional, but this is the closest to libadwaita's style you can get without removing the labels entirely or faking text by drawing images with text instead. The text as images workaround is already used in the overlay so maybe I'll try it here later.
