### ISSUE TITLE
Can't find "Recent Players" window in this skin.

### ISSUE THREAD

**Issue by kindagoose** [tkashkin/Adwaita-for-Steam#38]
It is very helpful in games such as Elden Ring or Dark Souls because you to see people who you met in multiplayer sessions.

In default skin it opens as a separate window, which can't be updated unless you reopen it. Would be awesome to have it as one of main tabs which also auto-updates if that's possible. Going thru menus to open it every time is frustrating.

**Comment by Foldex** [comment]
![overlay](https://user-images.githubusercontent.com/47908676/194774261-aba333e8-dbe1-43dd-96ec-fd656a13707e.png)
Recent players is available through the in game overlay, as for updating the contents I doubt the skin has any control over that.
That said it looks like right now the window is missing its close button and window controls. So that's an issue, especially if you need to reopen it to refresh.

![recent](https://user-images.githubusercontent.com/47908676/194774328-0fee70c7-1980-454c-b09c-75708a30248c.png)

![vanilla](https://user-images.githubusercontent.com/47908676/194774777-ac4ca799-958b-4eb4-981b-3acb8decf57d.png)

**Comment by kindagoose** [comment]
Oh, I don't use overlay at all, I have steam on separate space and I check it from there, would be good to be able to open it from steam window with a single click just as in overlay.

**Comment by PiiNGPooNG** [comment]
Add the following line to [steam.menu](/tkashkin/Adwaita-for-Steam/blob/master/Adwaita/resource/menus/steam.menu) to add the option to the menu dropdown

`ViewPlayerList 		{ text="#steam_menu_view_players" shellcmd="steam://friends/players" }`
