### ISSUE TITLE
Window doesn't fit on small low resolution display

### ISSUE THREAD

**Issue by abuhuraira0099** [tkashkin/Adwaita-for-Steam#5]
Window used to fit before the recent release, but after the last UI commit, it doesn't fit anymore. 
Gnome 43.alpha Wayland on 1024x768 (4:3) display.

![image](https://user-images.githubusercontent.com/79898595/183279912-bbcce09e-674c-4576-9043-3cf48a8a8b84.png)

**Comment by tkashkin** [comment]
I can decrease the minimum window width and center the navigation buttons in the free space instead of centering them in the full window:

![1](https://user-images.githubusercontent.com/2003017/183288544-3664ac7d-4dce-40d3-ad36-395df6507095.png)

This fixes your issue but starts to look weird when there is more space available:

![2](https://user-images.githubusercontent.com/2003017/183288550-8875d8ec-d8f7-4bbc-ab39-a78d6899f8ec.png)

It will become even more noticeable if you add minimize and maximize buttons to the right side.

I can always center the navigation buttons in window, then on small windows there will be a lot of empty space on the left side and buttons will be cut off on the right side:

![3](https://user-images.githubusercontent.com/2003017/183289124-cba33628-7197-498c-8aa3-bfb7c023977f.png)

I guess the best solution is to remove some of the buttons from the right side, though it will still be a problem if you add minimize and maximize buttons. And I'm not sure where else to put them.
