### ISSUE TITLE
Cannot enable skin

### ISSUE THREAD

**Issue by qwertychouskie** [tkashkin/Adwaita-for-Steam#64]
The skin show up in Steam's settings, but if I select it and allow Steam to restart, it just uses the default skin.

Ubuntu 22.10
RTX 3060 Mobile
Steam installed via `apt`
I was running the beta client, but disabled the beta client while trying to troubleshoot.

**Comment by tkashkin** [comment]
It should work if it's detected in Steam settings, not sure what could go wrong in this case.

I have one idea to verify:

> Steam installed via `apt`

Double check that. Maybe it's Ubuntu forcing a snap package when you think you use `apt`.
They did this for browsers and I remember reading that they've made a snap package of Steam recently, so maybe Ubuntu does the same thing for Steam now.

**Comment by CrisisModel** [comment]
I'm having this issue, too. Steam is installed via the official repos (Arch Linux) and the theme initially worked until it deactivated itself. I keep choosing it in the Steam settings and letting Steam restart, but the theme won't activate anymore.

**Comment by Foldex** [comment]
Can't really reproduce it on my end, but:
- Is the `Adwaita` dir correctly populated under the steam `skins` dir?
- Is there any relevant terminal output from steam/the installer?
- Does the skin work when manually installed instead of using the installer?
- Do other skins work when installed to the same location? You can try: [test-skin.zip](https://github.com/tkashkin/Adwaita-for-Steam/files/9843237/test-skin.zip)
- Check that the `~/.steam/steam` symlink exists and points to a valid steam directory.
- Make sure the steam `skins` directory itself isn't symlinked elsewhere, Steam doesn't like loading skin symlinks for some reason.

**Comment by qwertychouskie** [comment]
The issue is still present.  I confirmed the installation was successful, and Steam lists the skin as an option, but after selecting it and allowing Steam to restart, it just starts up with the stock skin.  The `~/.steam/steam` symlink exists and is valid, and the skins folder itself is a regular folder (not a symlink).

**Comment by Foldex** [comment]
![scrot](https://user-images.githubusercontent.com/47908676/209741174-4c9149ec-f803-4b8c-8041-1da20b8b939a.png)

Gave it a test in a fresh 22.10 VM, steam installed through apt. Still couldn't reproduce this, shrug.
@qwertychouskie 
Bit of a pain, but does this still occur if you move your steam folder and let steam rebuild it?

**Comment by tkashkin** [comment]
Can't reproduce and it's probably a Steam bug we can't fix anyway.

Feel free to reopen if the issue does not happen with other skins and somehow only happens with this one.

**Comment by qwertychouskie** [comment]
FWIW I just `git pull`ed the latest version of the theme and ran `./install.py`, and Steam now uses the theme.  Not sure if something changed with the theme, the installer, Steam itself, the Ubuntu Steam package, or what, but it works now.  A bit weird, but can't really complain ;)
